### ISSUE TITLE
USER STORY: Deploy Website

### ISSUE THREAD

**Issue by nathan-bytecode** [nathan-bytecode/midlands-soccer-lessons#1]
As a **developer** I can **deploy the website early** so that **I avoid any technical errors closer to submission**.

**Comment by nathan-bytecode** [comment]
### Acceptance Criteria

- The project must be deployed to Heroku
- The project must use a 3rd party to host images like Cloudinary
- The code must be stored in GitHub for the assessor to grade
- The project must be displayed through my Github app
- The project must use a 3rd party to store databases like ElephantSQL

### Tasks
- [x]  Create workspace with Gitpod
- [x]  Connect Github to Heroku
- [x]  Set up environment variables
- [x]  Connect Cloudinary
- [x]  Ensure app is showing deployed on Heroku
- [x] Connect ElephantSQL to use PostgreSQL
