### ISSUE TITLE
USER STORY: Base Template

### ISSUE THREAD

**Issue by nathan-bytecode** [nathan-bytecode/midlands-soccer-lessons#4]
As a **Developer** I can **view the website while coding it** so that **I can make adjustments and ensure a functionality works as expected.**

### Acceptance Criteria
- Project must include a base template
- Base template must have all required links, meta data and CDN's required for this project
- Must include the links and navigation adhering to Django URL rules

### Tasks
- [x]  Create base.html & add boiler plate code
- [x]  Add links to static files like CSS & JS
- [x]  Add CDN links in Head
