### ISSUE TITLE
USER STORY: Make a Booking

### ISSUE THREAD

**Issue by nathan-bytecode** [nathan-bytecode/midlands-soccer-lessons#5]
As a **Customer** I can **make a booking** so that **I can enroll my kids in a course and a preferred venue.**

### Acceptance Criteria

- User must have an account to make a booking
- User must have all required information on their profile(name, email, phone number)
- Admin must be able to see the reservation on the backend to approve
- User must be able to see reservation status from their profile

**Tasks**

- [x]  Create booking Model (create backend)
- [x]  Create booking form ( create functionality with HTML and CSS)
- [x]  Add booking details to users profile
