### ISSUE TITLE
USER STORY: Courses

### ISSUE THREAD

**Issue by nathan-bytecode** [nathan-bytecode/midlands-soccer-lessons#6]
As a **Business owner** I can **display current courses** so that **users can reserve tickets.**

**Acceptance Criteria**

- Users must have account
- Courses must open in a blog style page with image and content
- If the course has allocated all of its tickets then it will show as sold out and not be able to be booked.
- The admin must be able to view a list of attendees coming to the event
- The user must be able to see the event in their bookings list from their profile
- The user should be able to cancel their ticket if they can no longer attend and for it to return to the event portal.

### Tasks

- [x]  Create course models, URLs and logic (create backend)
- [x]  Create course links and pages ( create functionality with HTML and CSS)
- [x]  Add bookings to user profiles
- [x]  Allow user to cancel bookings
