### ISSUE TITLE
USER STORY: Delete Profile (CRUD)

### ISSUE THREAD

**Issue by nathan-bytecode** [nathan-bytecode/midlands-soccer-lessons#8]
As a **Customer** I can **delete my account** if I **no longer want to book any of the football lessons.**

### Acceptance Criteria

- User needs to be able to click a delete account option
- Defensive programming in place to prevent accidental deletion. (Modal)

### Tasks

- [ ]  Create delete logic in backend
- [ ]  Add delete account link to signed in user from profile page
- [ ]  Style delete account button so it stands out with a warning red color to prevent accidental click
- [ ]  Add pop up modal to confirm choice
