### ISSUE TITLE
USER STORY: Testing

### ISSUE THREAD

**Issue by nathan-bytecode** [nathan-bytecode/midlands-soccer-lessons#9]
As a **Developer** I can **test the website** so that **the end product is free from errors and ready to go live.**

### Acceptance Criteria

- The logic and backend code should be tested and free from errors
- The front end HTML and CSS should be tested and free from all errors
- All links should work and point to their desired action
- All images and aesthetic content should display in a clear and user friendly manner
- The website passes at a high score through Google Lighthouse
- The deployed website displays as intended on partner hosting
- All tests need to be documented in the readme either directly or in an intended tests file

### Tasks

- [ ]  Test backend code using Pep8 checker
- [ ]  Test frontend code
- [ ]  Test using Google Lighthouse
- [ ]  Get new users to run through sample testing on website
- [ ]  Collect results and score accordingly to success
- [ ]  Add feedback from users regarding UI improvements
- [ ]  Add all testing results and screenshots to Github repository
